Formatted fish helper scripts

diff --git a/scripts/build-to-copr b/scripts/build-to-copr
--- a/scripts/build-to-copr
+++ b/scripts/build-to-copr
@@ -19,36 +19,36 @@ Example:
 "
 
 switch (count $argv)
-  case 1
-    set -l name $argv[1]
+    case 1
+        set -l name $argv[1]
 
-    copr-cli buildscm \
-      --method make_srpm \
-      --clone-url 'https://github.com/kris3713/YACR.git' \
-      --commit 'master' \
-      --subdir "packages/$name" \
-      --spec "$name.spec" \
-      --enable-net 'on' \
-      'zliced13/YACR'
+        copr-cli buildscm \
+            --method make_srpm \
+            --clone-url 'https://github.com/kris3713/YACR.git' \
+            --commit master \
+            --subdir "packages/$name" \
+            --spec "$name.spec" \
+            --enable-net on \
+            zliced13/YACR
 
-  case 2
-    set -l subdir $argv[1]
-    set -l name $argv[2]
+    case 2
+        set -l subdir $argv[1]
+        set -l name $argv[2]
 
-    copr-cli buildscm \
-      --method make_srpm \
-      --clone-url 'https://github.com/kris3713/YACR.git' \
-      --commit 'master' \
-      --subdir "packages/$subdir" \
-      --spec "$name.spec" \
-      --enable-net 'on' \
-      'zliced13/YACR'
+        copr-cli buildscm \
+            --method make_srpm \
+            --clone-url 'https://github.com/kris3713/YACR.git' \
+            --commit master \
+            --subdir "packages/$subdir" \
+            --spec "$name.spec" \
+            --enable-net on \
+            zliced13/YACR
 
-  case '*'
-    set_color red
-    printf "ERROR: Invalid Usage!\n"
-    set_color normal
+    case '*'
+        set_color red
+        printf "ERROR: Invalid Usage!\n"
+        set_color normal
 
-    echo $msg
-    exit 1
+        echo $msg
+        exit 1
 end
diff --git a/scripts/change-packages b/scripts/change-packages
--- a/scripts/change-packages
+++ b/scripts/change-packages
@@ -25,105 +25,105 @@ Examples:
 "
 
 switch (count $argv)
-  case 1
-    set -l webhook_rebuild $argv[1]
+    case 1
+        set -l webhook_rebuild $argv[1]
 
-    if test $webhook_rebuild != 'on'; and test $webhook_rebuild != 'off'
-      echo 'First argument must either be a value of "on" or "off" (without quotes)'
-      exit 1
-    end
+        if test $webhook_rebuild != on; and test $webhook_rebuild != off
+            echo 'First argument must either be a value of "on" or "off" (without quotes)'
+            exit 1
+        end
 
-    for v in (fd 'spec' "$script_dir/../packages" -t file --format '{}')
-      # Get subdir name (ie. the directory that contains the spec file(s))
-      set -l split_dir (string split '/' $v)
-      set -l subdir $split_dir[-2]
-      set -l name (basename -s '.spec' $split_dir[-1])
+        for v in (fd 'spec' "$script_dir/../packages" -t file --format '{}')
+            # Get subdir name (ie. the directory that contains the spec file(s))
+            set -l split_dir (string split '/' $v)
+            set -l subdir $split_dir[-2]
+            set -l name (basename -s '.spec' $split_dir[-1])
 
-      echo '--------------------------------------------'
-      echo 'Method: make_srpm'
-      echo 'Clone URL: https://github.com/kris3713/YACR.git'
-      echo 'Commitish: master'
-      echo "Subdir: packages/$subdir"
-      echo "Spec: $name.spec"
-      echo "Pkg Name: $name"
-      echo "Webhook Rebuild: $webhook_rebuild"
-      echo 'COPR Project: zliced13/YACR'
+            echo --------------------------------------------
+            echo 'Method: make_srpm'
+            echo 'Clone URL: https://github.com/kris3713/YACR.git'
+            echo 'Commitish: master'
+            echo "Subdir: packages/$subdir"
+            echo "Spec: $name.spec"
+            echo "Pkg Name: $name"
+            echo "Webhook Rebuild: $webhook_rebuild"
+            echo 'COPR Project: zliced13/YACR'
 
-      copr-cli edit-package-scm \
-        --method make_srpm \
-        --clone-url 'https://github.com/kris3713/YACR.git' \
-        --commit master \
-        --subdir "packages/$subdir" \
-        --spec "$name.spec" \
-        --name $name \
-        --webhook-rebuild $webhook_rebuild \
-        'zliced13/YACR'
-    end
+            copr-cli edit-package-scm \
+                --method make_srpm \
+                --clone-url 'https://github.com/kris3713/YACR.git' \
+                --commit master \
+                --subdir "packages/$subdir" \
+                --spec "$name.spec" \
+                --name $name \
+                --webhook-rebuild $webhook_rebuild \
+                zliced13/YACR
+        end
 
-  case 2
-    set -l webhook_rebuild $argv[1]
-    set -l name $argv[2]
+    case 2
+        set -l webhook_rebuild $argv[1]
+        set -l name $argv[2]
 
-    if test $webhook_rebuild != 'on'; and test $webhook_rebuild != 'off'
-      echo 'First argument must either be a value of "on" or "off" (without quotes)'
-      exit 1
-    end
+        if test $webhook_rebuild != on; and test $webhook_rebuild != off
+            echo 'First argument must either be a value of "on" or "off" (without quotes)'
+            exit 1
+        end
 
-    echo '--------------------------------------------'
-    echo 'Method: make_srpm'
-    echo 'Clone URL: https://github.com/kris3713/YACR.git'
-    echo 'Commitish: master'
-    echo "Subdir: packages/$name"
-    echo "Spec: $name.spec"
-    echo "Pkg Name: $name"
-    echo "Webhook Rebuild: $webhook_rebuild"
-    echo 'COPR Project: zliced13/YACR'
+        echo --------------------------------------------
+        echo 'Method: make_srpm'
+        echo 'Clone URL: https://github.com/kris3713/YACR.git'
+        echo 'Commitish: master'
+        echo "Subdir: packages/$name"
+        echo "Spec: $name.spec"
+        echo "Pkg Name: $name"
+        echo "Webhook Rebuild: $webhook_rebuild"
+        echo 'COPR Project: zliced13/YACR'
 
-    copr-cli edit-package-scm \
-      --method make_srpm \
-      --clone-url 'https://github.com/kris3713/YACR.git' \
-      --commit master \
-      --subdir "packages/$name" \
-      --spec "$name.spec" \
-      --name $name \
-      --webhook-rebuild $webhook_rebuild \
-      'zliced13/YACR'
+        copr-cli edit-package-scm \
+            --method make_srpm \
+            --clone-url 'https://github.com/kris3713/YACR.git' \
+            --commit master \
+            --subdir "packages/$name" \
+            --spec "$name.spec" \
+            --name $name \
+            --webhook-rebuild $webhook_rebuild \
+            zliced13/YACR
 
-  case 3
-    set -l webhook_rebuild $argv[1]
-    set -l subdir $argv[2]
-    set -l name $argv[3]
+    case 3
+        set -l webhook_rebuild $argv[1]
+        set -l subdir $argv[2]
+        set -l name $argv[3]
 
-    if test $webhook_rebuild != 'on'; and test $webhook_rebuild != 'off'
-      echo 'First argument must either be a value of "on" or "off" (without quotes)'
-      exit 1
-    end
+        if test $webhook_rebuild != on; and test $webhook_rebuild != off
+            echo 'First argument must either be a value of "on" or "off" (without quotes)'
+            exit 1
+        end
 
-    echo '--------------------------------------------'
-    echo 'Method: make_srpm'
-    echo 'Clone URL: https://github.com/kris3713/YACR.git'
-    echo 'Commitish: master'
-    echo "Subdir: packages/$subdir"
-    echo "Spec: $name.spec"
-    echo "Pkg Name: $name"
-    echo "Webhook Rebuild: $webhook_rebuild"
-    echo 'COPR Project: zliced13/YACR'
+        echo --------------------------------------------
+        echo 'Method: make_srpm'
+        echo 'Clone URL: https://github.com/kris3713/YACR.git'
+        echo 'Commitish: master'
+        echo "Subdir: packages/$subdir"
+        echo "Spec: $name.spec"
+        echo "Pkg Name: $name"
+        echo "Webhook Rebuild: $webhook_rebuild"
+        echo 'COPR Project: zliced13/YACR'
 
-    copr-cli edit-package-scm \
-      --method make_srpm \
-      --clone-url 'https://github.com/kris3713/YACR.git' \
-      --commit master \
-      --subdir "packages/$subdir" \
-      --spec "$name.spec" \
-      --name $name \
-      --webhook-rebuild $webhook_rebuild \
-      'zliced13/YACR'
+        copr-cli edit-package-scm \
+            --method make_srpm \
+            --clone-url 'https://github.com/kris3713/YACR.git' \
+            --commit master \
+            --subdir "packages/$subdir" \
+            --spec "$name.spec" \
+            --name $name \
+            --webhook-rebuild $webhook_rebuild \
+            zliced13/YACR
 
-  case '*'
-    set_color red
-    printf 'ERROR: Invalid Usage!\n'
-    set_color normal
+    case '*'
+        set_color red
+        printf 'ERROR: Invalid Usage!\n'
+        set_color normal
 
-    echo $msg
-    exit 1
+        echo $msg
+        exit 1
 end
