Update update-packages.yml

diff --git a/.github/workflows/update-packages.yml b/.github/workflows/update-packages.yml
--- a/.github/workflows/update-packages.yml
+++ b/.github/workflows/update-packages.yml
@@ -70,6 +70,13 @@ jobs:
             chmod +x $i
             echo "Executing $i"; eval $i
             chmod -x $i
+            if [ "$?" -ne 0 ]; then
+              basename=$(basename $i)
+              echo "Failed to get the latest version for $basename"
+              unset basename
+              echo 'Exitting...'
+              exit 1
+            fi
             echo '---------------------------------------'
             echo '---------------------------------------'
           done
